QuantumPatch:
  morphology: morphology.cml
  convergence_criterion: steps
  partial_charge_cutoff: 60
  dimer_cutoff: 7.0
  number_of_equilibration_steps: 7
  charge_damping: 0.15
DFTEngine:
  defaults:
    Turbomole:
      basis: def2-SVP
      functional: b-p
      threads: 1
      memory: 1500
      reference: rdft
      charge_model: ESP
    Psi4Engine: sameas:DFTEngine.defaults.Turbomole
    DFTBplus:
      threads: 1
      charge_model: mulliken
      thirdorder: true
      skfset: 3ob-3-1
  charged:
    settings: sameas:DFTEngine.defaults.Turbomole
    name: Turbomole
  fallback:
    settings: sameas:DFTEngine.defaults.Turbomole
    name: Turbomole
    dofallback: false
System:
  Core:
Analysis:
  MatrixEAIP:
    radius: sameas:System.Shells.0.cutoff
  MachineLearning:
    enable: false
